services:
  api:
    image: mcr.microsoft.com/devcontainers/dotnet:1-8.0-bookworm
    volumes:
      - ../:/src
    depends_on:
      - db
    environment:
      DOTNET_ENVIRONMENT: Development
      ASPNETCORE_ENVIRONMENT: Development
    command: sleep infinity
  db:
    image: postgres:14-alpine
    ports:
      - "5432:5432"
    volumes:
      - ../db:/var/lib/postgresql/data
      - ./postgres/create-tables.sql:/docker-entrypoint-initdb.d/create_tables.sql
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
  adminer:
    image: adminer
    ports:
      - 8085:8080
